### ISSUE TITLE
can't pickle Grouplayer objects!!! GIMP 2.10

### ISSUE THREAD

**Issue by abdelbaribouhala** [d-j-a-y/Gimp2Synfig#14]
![screenshot from 2018-06-20 16-36-34](https://user-images.githubusercontent.com/40441880/41683283-2419535e-74a8-11e8-95c2-ec976835991c.png)
can't export any XCF project to SIF containing a grouplayer in GIMP 2.10. only if I delete all the grouplayers and hit Group in a single switch layer (synfig> =1.0) OPTION which I don't need by the way

**Comment by d-j-a-y** [comment]
thank's to report ... will try to have a look somedays.

**Comment by abdelbaribouhala** [comment]
thanks, we are waiting here!!!

**Comment by d-j-a-y** [comment]
i have done a bit of work, but seems not "simple" as i thought :-(

**Comment by d-j-a-y** [comment]
#1

**Comment by d-j-a-y** [comment]
I want to say ... it's a GIMP issue : [Unable to give a layer group as a parameter to a python script](https://gitlab.gnome.org/GNOME/gimp/issues/1119)

To by pass :  _you must select an active layer that IS NOT a layergroup for script to run properly to work around the "can't pickle" error._ [tim @ gimplearn.net](https://gimplearn.net/viewtopic.php/To-Legacy-Mode-Script-Plug-in?t=1649)

**Comment by BarbzYHOOL** [comment]
same issue and i don't understand what you mean @d-j-a-y is there a solution or it's just a bug that will stay ?

For me it happens when I enable "Group in a single switch layer"
