### ISSUE TITLE
What is image span?

### ISSUE THREAD

**Issue by BarbzYHOOL** [d-j-a-y/Gimp2Synfig#18]
I can't find any info about it :'(

**Comment by d-j-a-y** [comment]
Image span is [Synfig vocabulary](https://wiki.synfig.org/Canvas_Properties_Dialog)

**Comment by BarbzYHOOL** [comment]
yeah sorry, i got very confused by synfig, not your plugin in fact

I don't even understand what this means: `Image Span - diagonal size of the portion of the workarea`

**Comment by d-j-a-y** [comment]
>I don't even understand what this means: ....

Image Span - diagonal size of the portion of the workarea ("Top Left (X/Y)"² +"Bottom Right (X/Y)"² ="Image Span"² ) Aka [Pythagorean theorem](https://en.wikipedia.org/wiki/Pythagorean_theorem)

**Comment by BarbzYHOOL** [comment]
ah ok ty
