### ISSUE TITLE
Each image is inside an useless group in synfig

### ISSUE THREAD

**Issue by BarbzYHOOL** [d-j-a-y/Gimp2Synfig#19]
Each image is inside an useless group in synfig, is it normal?

I have to extract each image from the group when i'm in synfig,  is it a bug?

**Comment by d-j-a-y** [comment]
What do you mean by useless ? 

What do you mean by extract the image in synfig ? 

Can you share both Gimp and Synfig layer panel screenshot ?

**Comment by d-j-a-y** [comment]
@BarbzYHOOL ; also notice that you can group the image in a ["Switch layer"](https://wiki.synfig.org/Switch_Group_Layer)

**Comment by BarbzYHOOL** [comment]
extract image means move the image out of the group

sry i don't use synfig for now so can't give more info about why i said all of this above, i forgot
