### ISSUE TITLE
[Suggestion] Group of layers -> group of layers in synfig

### ISSUE THREAD

**Issue by BarbzYHOOL** [d-j-a-y/Gimp2Synfig#20]
It would be practical that when exporting, it transposes the group structure from Gimp to Synfig

**Comment by d-j-a-y** [comment]
#1

**Comment by BarbzYHOOL** [comment]
i think I tried the branch but it didn't change anything

Not sure I tested correctly though as the plugin bugged once or twice in gimp, and synfig bugged too
