### ISSUE TITLE
Plugin does not work on GIMP 2.10.20.

### ISSUE THREAD

**Issue by bauerbach** [d-j-a-y/Gimp2Synfig#21]
On GIMP 2.10.20, the plug-in is not recognized. "Synfig Studio" does not even show up in the File Extensions list on the Export Dialog, and the plug-in does not show up in the Plug-ins Browser either.

**Comment by d-j-a-y** [comment]
Thanks for reporting.

By the way, if the plugins is not well installed, the Gimp file extension list on export will not show sif/sfz/sfg synfig's files format.

**Comment by bitkleberAST** [comment]
Plug-In is not working on my Gimp 2.10.18 also.
Steps taken:
* Copied both .py files to the Gimp plugins directory
* installed Python
* created new  PYTHONPATH environment variable (which points to the Python executable)
* even copied *.py files into \pythonInstallation\scripts folder
* restarted Gimp

There is still no entry in the file extension list within Gimp. Am I doing something wrong?

**Comment by zhulei11223** [comment]
install gimp-python

**Comment by hellocatfood** [comment]
@zhulei11223 gimp-python relies on python2 which isn't shipped by several distributions as it's deprecated

**Comment by d-j-a-y** [comment]
python runtime related

**Comment by hellocatfood** [comment]
I see this has been labelled as wontfix. Considering that python2 has been dropped by many distributions *and* upcoming gimp versions (see #23 ) couldn't it be argued that this is still a valid bug?

**Comment by BarbzYHOOL** [comment]
@hellocatfood no, the problem is from gimp not updating to python3 and distribs not providing python2 for gimp

use the flatpak
