### ISSUE TITLE
Does not work for GIMP 2.10.24 (revision 3) OS: Windows

### ISSUE THREAD

**Issue by umarudkar** [d-j-a-y/Gimp2Synfig#22]
Does it support Windows?
I am using the latest version... GIMP 2.10.24, the option to export in Synfig extension does not show up.
Any solution?

**Comment by d-j-a-y** [comment]
Hi,

Can you confirm the visibility of "Python-fu" menu item entry from Menu/Filters ?
[Python-fu menu item missing from Filters menu](https://gitlab.gnome.org/GNOME/gimp/-/issues/5961)
